import { initializeApp } from 'firebase-admin/app';
initializeApp();
export { criarOuRetomarRascunho } from './commands/criarOuRetomarRascunho.js';
export { alterarAutoridadeAdministrativa } from './commands/gerenciarAutoridadeAdministrativa.js';
export { semearCatalogoInicial } from './commands/semearCatalogoInicial.js';
export { consultarCatalogo } from './commands/consultarCatalogo.js';
export { salvarPessoa } from './commands/salvarPessoa.js';
export { gerenciarPapeis } from './commands/gerenciarPapeis.js';
export { consultarPessoas } from './commands/consultarPessoas.js';
export { gerenciarVinculo } from './commands/gerenciarVinculo.js';
export { consultarVinculos } from './commands/consultarVinculos.js';
